overrides:
  '@isaacs/brace-expansion@<=5.0.0': '>=5.0.1'
  ajv@<6.14.0: '>=6.14.0'
  axios@>=1.0.0 <=1.13.4: '>=1.13.5'
  minimatch@<3.1.3: '>=3.1.3'
  minimatch@>=10.0.0 <10.2.1: '>=10.2.1'
  minimatch@>=9.0.0 <9.0.6: '>=9.0.6'
