/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DevRouteRouteImport } from './routes/dev/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UnitsIndexRouteImport } from './routes/units/index'
import { Route as TenantsIndexRouteImport } from './routes/tenants/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as PropsIndexRouteImport } from './routes/props/index'
import { Route as ProfileIndexRouteImport } from './routes/profile/index'
import { Route as MessagesIndexRouteImport } from './routes/messages/index'
import { Route as DevIndexRouteImport } from './routes/dev/index'
import { Route as UnitsUnitIdRouteImport } from './routes/units/$unitId'
import { Route as TenantsTenantIdRouteImport } from './routes/tenants/$tenantId'
import { Route as PublicTermsRouteImport } from './routes/public/terms'
import { Route as PublicPrivacyRouteImport } from './routes/public/privacy'
import { Route as InviteTokenRouteImport } from './routes/invite/$token'
import { Route as DevAuthRouteImport } from './routes/dev/auth'
import { Route as PropsIdRouteRouteImport } from './routes/props/$id/route'
import { Route as LeasesTemplatesRouteRouteImport } from './routes/leases/templates/route'
import { Route as LeasesAgreementsRouteRouteImport } from './routes/leases/agreements/route'
import { Route as PropsIdIndexRouteImport } from './routes/props/$id/index'
import { Route as PeopleVendorsIndexRouteImport } from './routes/people/vendors/index'
import { Route as PeopleOwnersIndexRouteImport } from './routes/people/owners/index'
import { Route as MaintenanceWorkOrdersIndexRouteImport } from './routes/maintenance/work-orders/index'
import { Route as MaintenanceRequestsIndexRouteImport } from './routes/maintenance/requests/index'
import { Route as LeasesTemplatesIndexRouteImport } from './routes/leases/templates/index'
import { Route as LeasesApplicationsIndexRouteImport } from './routes/leases/applications/index'
import { Route as LeasesAgreementsIndexRouteImport } from './routes/leases/agreements/index'
import { Route as FinanceTransactionsIndexRouteImport } from './routes/finance/transactions/index'
import { Route as FinanceReportsIndexRouteImport } from './routes/finance/reports/index'
import { Route as FinanceInvoicesIndexRouteImport } from './routes/finance/invoices/index'
import { Route as LeasesTemplatesTemplateIdRouteImport } from './routes/leases/templates/$templateId'
import { Route as LeasesAgreementsLeaseIdRouteImport } from './routes/leases/agreements/$leaseId'

const DevRouteRoute = DevRouteRouteImport.update({
  id: '/dev',
  path: '/dev',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UnitsIndexRoute = UnitsIndexRouteImport.update({
  id: '/units/',
  path: '/units/',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantsIndexRoute = TenantsIndexRouteImport.update({
  id: '/tenants/',
  path: '/tenants/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const PropsIndexRoute = PropsIndexRouteImport.update({
  id: '/props/',
  path: '/props/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesIndexRoute = MessagesIndexRouteImport.update({
  id: '/messages/',
  path: '/messages/',
  getParentRoute: () => rootRouteImport,
} as any)
const DevIndexRoute = DevIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DevRouteRoute,
} as any)
const UnitsUnitIdRoute = UnitsUnitIdRouteImport.update({
  id: '/units/$unitId',
  path: '/units/$unitId',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantsTenantIdRoute = TenantsTenantIdRouteImport.update({
  id: '/tenants/$tenantId',
  path: '/tenants/$tenantId',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicTermsRoute = PublicTermsRouteImport.update({
  id: '/public/terms',
  path: '/public/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicPrivacyRoute = PublicPrivacyRouteImport.update({
  id: '/public/privacy',
  path: '/public/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const DevAuthRoute = DevAuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => DevRouteRoute,
} as any)
const PropsIdRouteRoute = PropsIdRouteRouteImport.update({
  id: '/props/$id',
  path: '/props/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const LeasesTemplatesRouteRoute = LeasesTemplatesRouteRouteImport.update({
  id: '/leases/templates',
  path: '/leases/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const LeasesAgreementsRouteRoute = LeasesAgreementsRouteRouteImport.update({
  id: '/leases/agreements',
  path: '/leases/agreements',
  getParentRoute: () => rootRouteImport,
} as any)
const PropsIdIndexRoute = PropsIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PropsIdRouteRoute,
} as any)
const PeopleVendorsIndexRoute = PeopleVendorsIndexRouteImport.update({
  id: '/people/vendors/',
  path: '/people/vendors/',
  getParentRoute: () => rootRouteImport,
} as any)
const PeopleOwnersIndexRoute = PeopleOwnersIndexRouteImport.update({
  id: '/people/owners/',
  path: '/people/owners/',
  getParentRoute: () => rootRouteImport,
} as any)
const MaintenanceWorkOrdersIndexRoute =
  MaintenanceWorkOrdersIndexRouteImport.update({
    id: '/maintenance/work-orders/',
    path: '/maintenance/work-orders/',
    getParentRoute: () => rootRouteImport,
  } as any)
const MaintenanceRequestsIndexRoute =
  MaintenanceRequestsIndexRouteImport.update({
    id: '/maintenance/requests/',
    path: '/maintenance/requests/',
    getParentRoute: () => rootRouteImport,
  } as any)
const LeasesTemplatesIndexRoute = LeasesTemplatesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LeasesTemplatesRouteRoute,
} as any)
const LeasesApplicationsIndexRoute = LeasesApplicationsIndexRouteImport.update({
  id: '/leases/applications/',
  path: '/leases/applications/',
  getParentRoute: () => rootRouteImport,
} as any)
const LeasesAgreementsIndexRoute = LeasesAgreementsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LeasesAgreementsRouteRoute,
} as any)
const FinanceTransactionsIndexRoute =
  FinanceTransactionsIndexRouteImport.update({
    id: '/finance/transactions/',
    path: '/finance/transactions/',
    getParentRoute: () => rootRouteImport,
  } as any)
const FinanceReportsIndexRoute = FinanceReportsIndexRouteImport.update({
  id: '/finance/reports/',
  path: '/finance/reports/',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceInvoicesIndexRoute = FinanceInvoicesIndexRouteImport.update({
  id: '/finance/invoices/',
  path: '/finance/invoices/',
  getParentRoute: () => rootRouteImport,
} as any)
const LeasesTemplatesTemplateIdRoute =
  LeasesTemplatesTemplateIdRouteImport.update({
    id: '/$templateId',
    path: '/$templateId',
    getParentRoute: () => LeasesTemplatesRouteRoute,
  } as any)
const LeasesAgreementsLeaseIdRoute = LeasesAgreementsLeaseIdRouteImport.update({
  id: '/$leaseId',
  path: '/$leaseId',
  getParentRoute: () => LeasesAgreementsRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dev': typeof DevRouteRouteWithChildren
  '/leases/agreements': typeof LeasesAgreementsRouteRouteWithChildren
  '/leases/templates': typeof LeasesTemplatesRouteRouteWithChildren
  '/props/$id': typeof PropsIdRouteRouteWithChildren
  '/dev/auth': typeof DevAuthRoute
  '/invite/$token': typeof InviteTokenRoute
  '/public/privacy': typeof PublicPrivacyRoute
  '/public/terms': typeof PublicTermsRoute
  '/tenants/$tenantId': typeof TenantsTenantIdRoute
  '/units/$unitId': typeof UnitsUnitIdRoute
  '/dev/': typeof DevIndexRoute
  '/messages/': typeof MessagesIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/props/': typeof PropsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/tenants/': typeof TenantsIndexRoute
  '/units/': typeof UnitsIndexRoute
  '/leases/agreements/$leaseId': typeof LeasesAgreementsLeaseIdRoute
  '/leases/templates/$templateId': typeof LeasesTemplatesTemplateIdRoute
  '/finance/invoices/': typeof FinanceInvoicesIndexRoute
  '/finance/reports/': typeof FinanceReportsIndexRoute
  '/finance/transactions/': typeof FinanceTransactionsIndexRoute
  '/leases/agreements/': typeof LeasesAgreementsIndexRoute
  '/leases/applications/': typeof LeasesApplicationsIndexRoute
  '/leases/templates/': typeof LeasesTemplatesIndexRoute
  '/maintenance/requests/': typeof MaintenanceRequestsIndexRoute
  '/maintenance/work-orders/': typeof MaintenanceWorkOrdersIndexRoute
  '/people/owners/': typeof PeopleOwnersIndexRoute
  '/people/vendors/': typeof PeopleVendorsIndexRoute
  '/props/$id/': typeof PropsIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dev/auth': typeof DevAuthRoute
  '/invite/$token': typeof InviteTokenRoute
  '/public/privacy': typeof PublicPrivacyRoute
  '/public/terms': typeof PublicTermsRoute
  '/tenants/$tenantId': typeof TenantsTenantIdRoute
  '/units/$unitId': typeof UnitsUnitIdRoute
  '/dev': typeof DevIndexRoute
  '/messages': typeof MessagesIndexRoute
  '/profile': typeof ProfileIndexRoute
  '/props': typeof PropsIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/tenants': typeof TenantsIndexRoute
  '/units': typeof UnitsIndexRoute
  '/leases/agreements/$leaseId': typeof LeasesAgreementsLeaseIdRoute
  '/leases/templates/$templateId': typeof LeasesTemplatesTemplateIdRoute
  '/finance/invoices': typeof FinanceInvoicesIndexRoute
  '/finance/reports': typeof FinanceReportsIndexRoute
  '/finance/transactions': typeof FinanceTransactionsIndexRoute
  '/leases/agreements': typeof LeasesAgreementsIndexRoute
  '/leases/applications': typeof LeasesApplicationsIndexRoute
  '/leases/templates': typeof LeasesTemplatesIndexRoute
  '/maintenance/requests': typeof MaintenanceRequestsIndexRoute
  '/maintenance/work-orders': typeof MaintenanceWorkOrdersIndexRoute
  '/people/owners': typeof PeopleOwnersIndexRoute
  '/people/vendors': typeof PeopleVendorsIndexRoute
  '/props/$id': typeof PropsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dev': typeof DevRouteRouteWithChildren
  '/leases/agreements': typeof LeasesAgreementsRouteRouteWithChildren
  '/leases/templates': typeof LeasesTemplatesRouteRouteWithChildren
  '/props/$id': typeof PropsIdRouteRouteWithChildren
  '/dev/auth': typeof DevAuthRoute
  '/invite/$token': typeof InviteTokenRoute
  '/public/privacy': typeof PublicPrivacyRoute
  '/public/terms': typeof PublicTermsRoute
  '/tenants/$tenantId': typeof TenantsTenantIdRoute
  '/units/$unitId': typeof UnitsUnitIdRoute
  '/dev/': typeof DevIndexRoute
  '/messages/': typeof MessagesIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/props/': typeof PropsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/tenants/': typeof TenantsIndexRoute
  '/units/': typeof UnitsIndexRoute
  '/leases/agreements/$leaseId': typeof LeasesAgreementsLeaseIdRoute
  '/leases/templates/$templateId': typeof LeasesTemplatesTemplateIdRoute
  '/finance/invoices/': typeof FinanceInvoicesIndexRoute
  '/finance/reports/': typeof FinanceReportsIndexRoute
  '/finance/transactions/': typeof FinanceTransactionsIndexRoute
  '/leases/agreements/': typeof LeasesAgreementsIndexRoute
  '/leases/applications/': typeof LeasesApplicationsIndexRoute
  '/leases/templates/': typeof LeasesTemplatesIndexRoute
  '/maintenance/requests/': typeof MaintenanceRequestsIndexRoute
  '/maintenance/work-orders/': typeof MaintenanceWorkOrdersIndexRoute
  '/people/owners/': typeof PeopleOwnersIndexRoute
  '/people/vendors/': typeof PeopleVendorsIndexRoute
  '/props/$id/': typeof PropsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dev'
    | '/leases/agreements'
    | '/leases/templates'
    | '/props/$id'
    | '/dev/auth'
    | '/invite/$token'
    | '/public/privacy'
    | '/public/terms'
    | '/tenants/$tenantId'
    | '/units/$unitId'
    | '/dev/'
    | '/messages/'
    | '/profile/'
    | '/props/'
    | '/settings/'
    | '/tenants/'
    | '/units/'
    | '/leases/agreements/$leaseId'
    | '/leases/templates/$templateId'
    | '/finance/invoices/'
    | '/finance/reports/'
    | '/finance/transactions/'
    | '/leases/agreements/'
    | '/leases/applications/'
    | '/leases/templates/'
    | '/maintenance/requests/'
    | '/maintenance/work-orders/'
    | '/people/owners/'
    | '/people/vendors/'
    | '/props/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dev/auth'
    | '/invite/$token'
    | '/public/privacy'
    | '/public/terms'
    | '/tenants/$tenantId'
    | '/units/$unitId'
    | '/dev'
    | '/messages'
    | '/profile'
    | '/props'
    | '/settings'
    | '/tenants'
    | '/units'
    | '/leases/agreements/$leaseId'
    | '/leases/templates/$templateId'
    | '/finance/invoices'
    | '/finance/reports'
    | '/finance/transactions'
    | '/leases/agreements'
    | '/leases/applications'
    | '/leases/templates'
    | '/maintenance/requests'
    | '/maintenance/work-orders'
    | '/people/owners'
    | '/people/vendors'
    | '/props/$id'
  id:
    | '__root__'
    | '/'
    | '/dev'
    | '/leases/agreements'
    | '/leases/templates'
    | '/props/$id'
    | '/dev/auth'
    | '/invite/$token'
    | '/public/privacy'
    | '/public/terms'
    | '/tenants/$tenantId'
    | '/units/$unitId'
    | '/dev/'
    | '/messages/'
    | '/profile/'
    | '/props/'
    | '/settings/'
    | '/tenants/'
    | '/units/'
    | '/leases/agreements/$leaseId'
    | '/leases/templates/$templateId'
    | '/finance/invoices/'
    | '/finance/reports/'
    | '/finance/transactions/'
    | '/leases/agreements/'
    | '/leases/applications/'
    | '/leases/templates/'
    | '/maintenance/requests/'
    | '/maintenance/work-orders/'
    | '/people/owners/'
    | '/people/vendors/'
    | '/props/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DevRouteRoute: typeof DevRouteRouteWithChildren
  LeasesAgreementsRouteRoute: typeof LeasesAgreementsRouteRouteWithChildren
  LeasesTemplatesRouteRoute: typeof LeasesTemplatesRouteRouteWithChildren
  PropsIdRouteRoute: typeof PropsIdRouteRouteWithChildren
  InviteTokenRoute: typeof InviteTokenRoute
  PublicPrivacyRoute: typeof PublicPrivacyRoute
  PublicTermsRoute: typeof PublicTermsRoute
  TenantsTenantIdRoute: typeof TenantsTenantIdRoute
  UnitsUnitIdRoute: typeof UnitsUnitIdRoute
  MessagesIndexRoute: typeof MessagesIndexRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
  PropsIndexRoute: typeof PropsIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  TenantsIndexRoute: typeof TenantsIndexRoute
  UnitsIndexRoute: typeof UnitsIndexRoute
  FinanceInvoicesIndexRoute: typeof FinanceInvoicesIndexRoute
  FinanceReportsIndexRoute: typeof FinanceReportsIndexRoute
  FinanceTransactionsIndexRoute: typeof FinanceTransactionsIndexRoute
  LeasesApplicationsIndexRoute: typeof LeasesApplicationsIndexRoute
  MaintenanceRequestsIndexRoute: typeof MaintenanceRequestsIndexRoute
  MaintenanceWorkOrdersIndexRoute: typeof MaintenanceWorkOrdersIndexRoute
  PeopleOwnersIndexRoute: typeof PeopleOwnersIndexRoute
  PeopleVendorsIndexRoute: typeof PeopleVendorsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dev': {
      id: '/dev'
      path: '/dev'
      fullPath: '/dev'
      preLoaderRoute: typeof DevRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/units/': {
      id: '/units/'
      path: '/units'
      fullPath: '/units/'
      preLoaderRoute: typeof UnitsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenants/': {
      id: '/tenants/'
      path: '/tenants'
      fullPath: '/tenants/'
      preLoaderRoute: typeof TenantsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/props/': {
      id: '/props/'
      path: '/props'
      fullPath: '/props/'
      preLoaderRoute: typeof PropsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/': {
      id: '/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages/': {
      id: '/messages/'
      path: '/messages'
      fullPath: '/messages/'
      preLoaderRoute: typeof MessagesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/': {
      id: '/dev/'
      path: '/'
      fullPath: '/dev/'
      preLoaderRoute: typeof DevIndexRouteImport
      parentRoute: typeof DevRouteRoute
    }
    '/units/$unitId': {
      id: '/units/$unitId'
      path: '/units/$unitId'
      fullPath: '/units/$unitId'
      preLoaderRoute: typeof UnitsUnitIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenants/$tenantId': {
      id: '/tenants/$tenantId'
      path: '/tenants/$tenantId'
      fullPath: '/tenants/$tenantId'
      preLoaderRoute: typeof TenantsTenantIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/public/terms': {
      id: '/public/terms'
      path: '/public/terms'
      fullPath: '/public/terms'
      preLoaderRoute: typeof PublicTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/public/privacy': {
      id: '/public/privacy'
      path: '/public/privacy'
      fullPath: '/public/privacy'
      preLoaderRoute: typeof PublicPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/auth': {
      id: '/dev/auth'
      path: '/auth'
      fullPath: '/dev/auth'
      preLoaderRoute: typeof DevAuthRouteImport
      parentRoute: typeof DevRouteRoute
    }
    '/props/$id': {
      id: '/props/$id'
      path: '/props/$id'
      fullPath: '/props/$id'
      preLoaderRoute: typeof PropsIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leases/templates': {
      id: '/leases/templates'
      path: '/leases/templates'
      fullPath: '/leases/templates'
      preLoaderRoute: typeof LeasesTemplatesRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leases/agreements': {
      id: '/leases/agreements'
      path: '/leases/agreements'
      fullPath: '/leases/agreements'
      preLoaderRoute: typeof LeasesAgreementsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/props/$id/': {
      id: '/props/$id/'
      path: '/'
      fullPath: '/props/$id/'
      preLoaderRoute: typeof PropsIdIndexRouteImport
      parentRoute: typeof PropsIdRouteRoute
    }
    '/people/vendors/': {
      id: '/people/vendors/'
      path: '/people/vendors'
      fullPath: '/people/vendors/'
      preLoaderRoute: typeof PeopleVendorsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/people/owners/': {
      id: '/people/owners/'
      path: '/people/owners'
      fullPath: '/people/owners/'
      preLoaderRoute: typeof PeopleOwnersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maintenance/work-orders/': {
      id: '/maintenance/work-orders/'
      path: '/maintenance/work-orders'
      fullPath: '/maintenance/work-orders/'
      preLoaderRoute: typeof MaintenanceWorkOrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maintenance/requests/': {
      id: '/maintenance/requests/'
      path: '/maintenance/requests'
      fullPath: '/maintenance/requests/'
      preLoaderRoute: typeof MaintenanceRequestsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leases/templates/': {
      id: '/leases/templates/'
      path: '/'
      fullPath: '/leases/templates/'
      preLoaderRoute: typeof LeasesTemplatesIndexRouteImport
      parentRoute: typeof LeasesTemplatesRouteRoute
    }
    '/leases/applications/': {
      id: '/leases/applications/'
      path: '/leases/applications'
      fullPath: '/leases/applications/'
      preLoaderRoute: typeof LeasesApplicationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leases/agreements/': {
      id: '/leases/agreements/'
      path: '/'
      fullPath: '/leases/agreements/'
      preLoaderRoute: typeof LeasesAgreementsIndexRouteImport
      parentRoute: typeof LeasesAgreementsRouteRoute
    }
    '/finance/transactions/': {
      id: '/finance/transactions/'
      path: '/finance/transactions'
      fullPath: '/finance/transactions/'
      preLoaderRoute: typeof FinanceTransactionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance/reports/': {
      id: '/finance/reports/'
      path: '/finance/reports'
      fullPath: '/finance/reports/'
      preLoaderRoute: typeof FinanceReportsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance/invoices/': {
      id: '/finance/invoices/'
      path: '/finance/invoices'
      fullPath: '/finance/invoices/'
      preLoaderRoute: typeof FinanceInvoicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leases/templates/$templateId': {
      id: '/leases/templates/$templateId'
      path: '/$templateId'
      fullPath: '/leases/templates/$templateId'
      preLoaderRoute: typeof LeasesTemplatesTemplateIdRouteImport
      parentRoute: typeof LeasesTemplatesRouteRoute
    }
    '/leases/agreements/$leaseId': {
      id: '/leases/agreements/$leaseId'
      path: '/$leaseId'
      fullPath: '/leases/agreements/$leaseId'
      preLoaderRoute: typeof LeasesAgreementsLeaseIdRouteImport
      parentRoute: typeof LeasesAgreementsRouteRoute
    }
  }
}

interface DevRouteRouteChildren {
  DevAuthRoute: typeof DevAuthRoute
  DevIndexRoute: typeof DevIndexRoute
}

const DevRouteRouteChildren: DevRouteRouteChildren = {
  DevAuthRoute: DevAuthRoute,
  DevIndexRoute: DevIndexRoute,
}

const DevRouteRouteWithChildren = DevRouteRoute._addFileChildren(
  DevRouteRouteChildren,
)

interface LeasesAgreementsRouteRouteChildren {
  LeasesAgreementsLeaseIdRoute: typeof LeasesAgreementsLeaseIdRoute
  LeasesAgreementsIndexRoute: typeof LeasesAgreementsIndexRoute
}

const LeasesAgreementsRouteRouteChildren: LeasesAgreementsRouteRouteChildren = {
  LeasesAgreementsLeaseIdRoute: LeasesAgreementsLeaseIdRoute,
  LeasesAgreementsIndexRoute: LeasesAgreementsIndexRoute,
}

const LeasesAgreementsRouteRouteWithChildren =
  LeasesAgreementsRouteRoute._addFileChildren(
    LeasesAgreementsRouteRouteChildren,
  )

interface LeasesTemplatesRouteRouteChildren {
  LeasesTemplatesTemplateIdRoute: typeof LeasesTemplatesTemplateIdRoute
  LeasesTemplatesIndexRoute: typeof LeasesTemplatesIndexRoute
}

const LeasesTemplatesRouteRouteChildren: LeasesTemplatesRouteRouteChildren = {
  LeasesTemplatesTemplateIdRoute: LeasesTemplatesTemplateIdRoute,
  LeasesTemplatesIndexRoute: LeasesTemplatesIndexRoute,
}

const LeasesTemplatesRouteRouteWithChildren =
  LeasesTemplatesRouteRoute._addFileChildren(LeasesTemplatesRouteRouteChildren)

interface PropsIdRouteRouteChildren {
  PropsIdIndexRoute: typeof PropsIdIndexRoute
}

const PropsIdRouteRouteChildren: PropsIdRouteRouteChildren = {
  PropsIdIndexRoute: PropsIdIndexRoute,
}

const PropsIdRouteRouteWithChildren = PropsIdRouteRoute._addFileChildren(
  PropsIdRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DevRouteRoute: DevRouteRouteWithChildren,
  LeasesAgreementsRouteRoute: LeasesAgreementsRouteRouteWithChildren,
  LeasesTemplatesRouteRoute: LeasesTemplatesRouteRouteWithChildren,
  PropsIdRouteRoute: PropsIdRouteRouteWithChildren,
  InviteTokenRoute: InviteTokenRoute,
  PublicPrivacyRoute: PublicPrivacyRoute,
  PublicTermsRoute: PublicTermsRoute,
  TenantsTenantIdRoute: TenantsTenantIdRoute,
  UnitsUnitIdRoute: UnitsUnitIdRoute,
  MessagesIndexRoute: MessagesIndexRoute,
  ProfileIndexRoute: ProfileIndexRoute,
  PropsIndexRoute: PropsIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  TenantsIndexRoute: TenantsIndexRoute,
  UnitsIndexRoute: UnitsIndexRoute,
  FinanceInvoicesIndexRoute: FinanceInvoicesIndexRoute,
  FinanceReportsIndexRoute: FinanceReportsIndexRoute,
  FinanceTransactionsIndexRoute: FinanceTransactionsIndexRoute,
  LeasesApplicationsIndexRoute: LeasesApplicationsIndexRoute,
  MaintenanceRequestsIndexRoute: MaintenanceRequestsIndexRoute,
  MaintenanceWorkOrdersIndexRoute: MaintenanceWorkOrdersIndexRoute,
  PeopleOwnersIndexRoute: PeopleOwnersIndexRoute,
  PeopleVendorsIndexRoute: PeopleVendorsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
