/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DevRouteRouteImport } from './routes/dev/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UnitsIndexRouteImport } from './routes/units/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as PropsIndexRouteImport } from './routes/props/index'
import { Route as ProfileIndexRouteImport } from './routes/profile/index'
import { Route as MessagesIndexRouteImport } from './routes/messages/index'
import { Route as DevIndexRouteImport } from './routes/dev/index'
import { Route as UnitsUnitIdRouteImport } from './routes/units/$unitId'
import { Route as PublicTermsRouteImport } from './routes/public/terms'
import { Route as PublicPrivacyRouteImport } from './routes/public/privacy'
import { Route as DevAuthRouteImport } from './routes/dev/auth'
import { Route as PropsIdRouteRouteImport } from './routes/props/$id/route'
import { Route as PropsIdIndexRouteImport } from './routes/props/$id/index'

const DevRouteRoute = DevRouteRouteImport.update({
  id: '/dev',
  path: '/dev',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UnitsIndexRoute = UnitsIndexRouteImport.update({
  id: '/units/',
  path: '/units/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const PropsIndexRoute = PropsIndexRouteImport.update({
  id: '/props/',
  path: '/props/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesIndexRoute = MessagesIndexRouteImport.update({
  id: '/messages/',
  path: '/messages/',
  getParentRoute: () => rootRouteImport,
} as any)
const DevIndexRoute = DevIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DevRouteRoute,
} as any)
const UnitsUnitIdRoute = UnitsUnitIdRouteImport.update({
  id: '/units/$unitId',
  path: '/units/$unitId',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicTermsRoute = PublicTermsRouteImport.update({
  id: '/public/terms',
  path: '/public/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicPrivacyRoute = PublicPrivacyRouteImport.update({
  id: '/public/privacy',
  path: '/public/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const DevAuthRoute = DevAuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => DevRouteRoute,
} as any)
const PropsIdRouteRoute = PropsIdRouteRouteImport.update({
  id: '/props/$id',
  path: '/props/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PropsIdIndexRoute = PropsIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PropsIdRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dev': typeof DevRouteRouteWithChildren
  '/props/$id': typeof PropsIdRouteRouteWithChildren
  '/dev/auth': typeof DevAuthRoute
  '/public/privacy': typeof PublicPrivacyRoute
  '/public/terms': typeof PublicTermsRoute
  '/units/$unitId': typeof UnitsUnitIdRoute
  '/dev/': typeof DevIndexRoute
  '/messages/': typeof MessagesIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/props/': typeof PropsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/units/': typeof UnitsIndexRoute
  '/props/$id/': typeof PropsIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dev/auth': typeof DevAuthRoute
  '/public/privacy': typeof PublicPrivacyRoute
  '/public/terms': typeof PublicTermsRoute
  '/units/$unitId': typeof UnitsUnitIdRoute
  '/dev': typeof DevIndexRoute
  '/messages': typeof MessagesIndexRoute
  '/profile': typeof ProfileIndexRoute
  '/props': typeof PropsIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/units': typeof UnitsIndexRoute
  '/props/$id': typeof PropsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dev': typeof DevRouteRouteWithChildren
  '/props/$id': typeof PropsIdRouteRouteWithChildren
  '/dev/auth': typeof DevAuthRoute
  '/public/privacy': typeof PublicPrivacyRoute
  '/public/terms': typeof PublicTermsRoute
  '/units/$unitId': typeof UnitsUnitIdRoute
  '/dev/': typeof DevIndexRoute
  '/messages/': typeof MessagesIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/props/': typeof PropsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/units/': typeof UnitsIndexRoute
  '/props/$id/': typeof PropsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dev'
    | '/props/$id'
    | '/dev/auth'
    | '/public/privacy'
    | '/public/terms'
    | '/units/$unitId'
    | '/dev/'
    | '/messages/'
    | '/profile/'
    | '/props/'
    | '/settings/'
    | '/units/'
    | '/props/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dev/auth'
    | '/public/privacy'
    | '/public/terms'
    | '/units/$unitId'
    | '/dev'
    | '/messages'
    | '/profile'
    | '/props'
    | '/settings'
    | '/units'
    | '/props/$id'
  id:
    | '__root__'
    | '/'
    | '/dev'
    | '/props/$id'
    | '/dev/auth'
    | '/public/privacy'
    | '/public/terms'
    | '/units/$unitId'
    | '/dev/'
    | '/messages/'
    | '/profile/'
    | '/props/'
    | '/settings/'
    | '/units/'
    | '/props/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DevRouteRoute: typeof DevRouteRouteWithChildren
  PropsIdRouteRoute: typeof PropsIdRouteRouteWithChildren
  PublicPrivacyRoute: typeof PublicPrivacyRoute
  PublicTermsRoute: typeof PublicTermsRoute
  UnitsUnitIdRoute: typeof UnitsUnitIdRoute
  MessagesIndexRoute: typeof MessagesIndexRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
  PropsIndexRoute: typeof PropsIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  UnitsIndexRoute: typeof UnitsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dev': {
      id: '/dev'
      path: '/dev'
      fullPath: '/dev'
      preLoaderRoute: typeof DevRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/units/': {
      id: '/units/'
      path: '/units'
      fullPath: '/units/'
      preLoaderRoute: typeof UnitsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/props/': {
      id: '/props/'
      path: '/props'
      fullPath: '/props/'
      preLoaderRoute: typeof PropsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/': {
      id: '/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages/': {
      id: '/messages/'
      path: '/messages'
      fullPath: '/messages/'
      preLoaderRoute: typeof MessagesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/': {
      id: '/dev/'
      path: '/'
      fullPath: '/dev/'
      preLoaderRoute: typeof DevIndexRouteImport
      parentRoute: typeof DevRouteRoute
    }
    '/units/$unitId': {
      id: '/units/$unitId'
      path: '/units/$unitId'
      fullPath: '/units/$unitId'
      preLoaderRoute: typeof UnitsUnitIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/public/terms': {
      id: '/public/terms'
      path: '/public/terms'
      fullPath: '/public/terms'
      preLoaderRoute: typeof PublicTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/public/privacy': {
      id: '/public/privacy'
      path: '/public/privacy'
      fullPath: '/public/privacy'
      preLoaderRoute: typeof PublicPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/auth': {
      id: '/dev/auth'
      path: '/auth'
      fullPath: '/dev/auth'
      preLoaderRoute: typeof DevAuthRouteImport
      parentRoute: typeof DevRouteRoute
    }
    '/props/$id': {
      id: '/props/$id'
      path: '/props/$id'
      fullPath: '/props/$id'
      preLoaderRoute: typeof PropsIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/props/$id/': {
      id: '/props/$id/'
      path: '/'
      fullPath: '/props/$id/'
      preLoaderRoute: typeof PropsIdIndexRouteImport
      parentRoute: typeof PropsIdRouteRoute
    }
  }
}

interface DevRouteRouteChildren {
  DevAuthRoute: typeof DevAuthRoute
  DevIndexRoute: typeof DevIndexRoute
}

const DevRouteRouteChildren: DevRouteRouteChildren = {
  DevAuthRoute: DevAuthRoute,
  DevIndexRoute: DevIndexRoute,
}

const DevRouteRouteWithChildren = DevRouteRoute._addFileChildren(
  DevRouteRouteChildren,
)

interface PropsIdRouteRouteChildren {
  PropsIdIndexRoute: typeof PropsIdIndexRoute
}

const PropsIdRouteRouteChildren: PropsIdRouteRouteChildren = {
  PropsIdIndexRoute: PropsIdIndexRoute,
}

const PropsIdRouteRouteWithChildren = PropsIdRouteRoute._addFileChildren(
  PropsIdRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DevRouteRoute: DevRouteRouteWithChildren,
  PropsIdRouteRoute: PropsIdRouteRouteWithChildren,
  PublicPrivacyRoute: PublicPrivacyRoute,
  PublicTermsRoute: PublicTermsRoute,
  UnitsUnitIdRoute: UnitsUnitIdRoute,
  MessagesIndexRoute: MessagesIndexRoute,
  ProfileIndexRoute: ProfileIndexRoute,
  PropsIndexRoute: PropsIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  UnitsIndexRoute: UnitsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
